<?php $notification = $this->getNotification(); ?>

<?php if ($notification->getId()): ?>

    <style>
        #forkel_bars_adminhtml_notification {
            color: <?php echo $notification->getColor() ?>;
            overflow: hidden;
            font-size: 1.2em;
            text-align: left;
            padding: 1em 1.5em;
            background: repeating-linear-gradient(
            45deg,
                <?php echo $this->getBackgroundLighter($notification->getColorBackground(), '20') ?>,
                <?php echo $this->getBackgroundLighter($notification->getColorBackground(), '20') ?> 10px,
                <?php echo $notification->getColorBackground() ?> 10px,
                <?php echo $notification->getColorBackground() ?> 20px
            );
        }
    </style>

    <div id="forkel_bars_adminhtml_notification">
        <?php echo $notification->getServerName(); ?>:
        <?php echo $notification->getName(); ?>
        <?php echo $notification->getDescription(); ?>
    </div>

<?php endif; ?>
